name: Forwardport Documentation

on:
  pull_request_target:
    types: ["labeled", "closed"]
    paths:
      - 'vcluster_versioned_docs/**'
      - 'platform_versioned_docs/**'

jobs:
  forwardport:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true ||
        (github.event.action == 'labeled' && github.event.label.name == 'forwardport-main')
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: loft-sh/docs-forwardport-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
